# Generated by Django 5.2.8 on 2025-12-23 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='profile',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='gender',
            field=models.CharField(blank=True, choices=[('ذكر', 'Male'), ('أنثى', 'Female')], max_length=10),
        ),
        migrations.AddField(
            model_name='profile',
            name='qualification',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
