# Generated by Django 5.2.8 on 2026-06-29 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_profile_external_id_profile_external_source_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('manager', 'Manager'), ('user', 'User'), ('employee', 'Employee'), ('beneficiary', 'Beneficiary'), ('supplier', 'Supplier'), ('representative', 'Representative'), ('donor', 'Donor')], default='user', max_length=20),
        ),
    ]
