# Generated by Django 5.2.15 on 2026-08-30 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_notification_center'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='notificationpreference',
            new_name='notificatio_user_id_a544c1_idx',
            old_name='notificatio_user_id_pref_idx',
        ),
    ]
