# Generated by Django 5.2.15 on 2026-08-09 05:27

import projects.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_seed_projects'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='donation_label',
            field=models.CharField(blank=True, default='تبرع الآن', max_length=100),
        ),
        migrations.AddField(
            model_name='project',
            name='donation_url',
            field=models.URLField(blank=True, help_text='رابط تبرع خاص بالمشروع (HTTPS فقط)', validators=[projects.validators.validate_https_donation_url]),
        ),
    ]
