# Generated by Django 5.2.15 on 2026-08-17 05:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_donation_links'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='featured_order',
            field=models.PositiveIntegerField(default=0, help_text='ترتيب العرض بين المشاريع المميزة (الأصغر أولاً)'),
        ),
        migrations.AddField(
            model_name='project',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='عرض في قسم المشاريع النشطة بالصفحة الرئيسية'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['is_featured', 'featured_order'], name='projects_pr_is_feat_5f7381_idx'),
        ),
    ]
