# Generated by Django 5.2.15 on 2026-08-01 14:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('analytics', '0001_initial'),
        # الجداول الفعلية أنشأتها هجرات takaful_app — يجب أن تسبق هذا النقل
        ('takaful_app', '0015_project_budget_project_external_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    # نقل نماذج بين تطبيقات دون لمس البيانات (DECISIONS.md D-02):
    # عمليات حالة فقط — الجداول الفعلية تبقى كما أنشأتها هجرات التطبيق الأصلي.
    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name='Service',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('title', models.CharField(max_length=200)),
                        ('desc', models.TextField(blank=True)),
                        ('status', models.CharField(choices=[('متاحة', 'متاحة'), ('قادمة', 'قادمة'), ('مكتملة', 'مكتملة')], default='متاحة', max_length=20)),
                        ('service_type', models.CharField(choices=[('للمستفيدين', 'للمستفيدين'), ('للمتطوعين', 'للمتطوعين')], default='للمتطوعين', max_length=20)),
                        ('is_active', models.BooleanField(default=True)),
                        ('created_at', models.DateTimeField(auto_now_add=True)),
                    ],
                    options={
                        'db_table': 'takaful_app_service',
                    },
                ),
                migrations.CreateModel(
                    name='Suggestion',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('title', models.CharField(max_length=200)),
                        ('description', models.TextField()),
                        ('submitted_by', models.CharField(blank=True, max_length=150)),
                        ('created_at', models.DateTimeField(auto_now_add=True)),
                        ('is_reviewed', models.BooleanField(default=False)),
                    ],
                    options={
                        'db_table': 'takaful_app_suggestion',
                    },
                ),
                migrations.CreateModel(
                    name='Volunteer',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('full_name', models.CharField(max_length=200)),
                        ('phone', models.CharField(blank=True, max_length=50)),
                        ('email', models.EmailField(blank=True, max_length=254)),
                        ('is_active', models.BooleanField(default=True)),
                        ('created_at', models.DateTimeField(auto_now_add=True)),
                    ],
                    options={
                        'db_table': 'takaful_app_volunteer',
                    },
                ),
                migrations.CreateModel(
                    name='VolunteerStatistics',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('year', models.IntegerField(unique=True)),
                        ('total_volunteers', models.IntegerField(default=0)),
                        ('new_volunteers', models.IntegerField(default=0)),
                        ('returning_volunteers', models.IntegerField(default=0)),
                        ('total_hours', models.IntegerField(default=0)),
                        ('total_contribution_value', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                        ('contribution_value_display', models.CharField(blank=True, max_length=50)),
                        ('created_at', models.DateTimeField(auto_now_add=True)),
                        ('updated_at', models.DateTimeField(auto_now=True)),
                    ],
                    options={
                        'verbose_name_plural': 'Volunteer Statistics',
                        'db_table': 'takaful_app_volunteerstatistics',
                        'ordering': ['-year'],
                    },
                ),
                migrations.CreateModel(
                    name='WaterSupplyRequest',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('applicant_name', models.CharField(max_length=200)),
                        ('mobile_number', models.CharField(max_length=20)),
                        ('applicant_role', models.CharField(choices=[('إمام', 'إمام'), ('مؤذن', 'مؤذن'), ('غير ذلك', 'غير ذلك')], max_length=50)),
                        ('mosque_name', models.CharField(max_length=200)),
                        ('neighborhood', models.CharField(max_length=200)),
                        ('location_link', models.URLField(max_length=500)),
                        ('worshippers_count', models.IntegerField()),
                        ('donor_exists', models.BooleanField(default=False)),
                        ('donor_name', models.CharField(blank=True, max_length=200)),
                        ('donor_phone', models.CharField(blank=True, max_length=20)),
                        ('status', models.CharField(choices=[('PENDING', 'قيد المراجعة'), ('APPROVED', 'مقبول'), ('REJECTED', 'مرفوض'), ('COMPLETED', 'مكتمل')], default='PENDING', max_length=20)),
                        ('admin_notes', models.TextField(blank=True)),
                        ('created_at', models.DateTimeField(auto_now_add=True)),
                        ('updated_at', models.DateTimeField(auto_now=True)),
                    ],
                    options={
                        'db_table': 'takaful_app_watersupplyrequest',
                        'ordering': ['-created_at'],
                    },
                ),
                migrations.CreateModel(
                    name='AdminReport',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('title', models.CharField(max_length=200)),
                        ('date_from', models.DateField(blank=True, null=True)),
                        ('date_to', models.DateField(blank=True, null=True)),
                        ('report_data', models.JSONField(default=dict)),
                        ('total_projects', models.IntegerField(default=0)),
                        ('total_volunteers', models.IntegerField(default=0)),
                        ('total_tasks', models.IntegerField(default=0)),
                        ('total_beneficiaries', models.IntegerField(default=0)),
                        ('total_donations', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                        ('generated_at', models.DateTimeField(auto_now_add=True)),
                        ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generated_reports', to=settings.AUTH_USER_MODEL)),
                    ],
                    options={
                        'db_table': 'takaful_app_adminreport',
                        'ordering': ['-generated_at'],
                    },
                ),
                migrations.CreateModel(
                    name='Project',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('title', models.CharField(max_length=200)),
                        ('desc', models.TextField(blank=True)),
                        ('category', models.CharField(blank=True, max_length=50)),
                        ('target_audience', models.CharField(blank=True, max_length=200)),
                        ('beneficiaries', models.IntegerField(default=0)),
                        ('location', models.CharField(blank=True, max_length=200)),
                        ('donation_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                        ('start_date', models.DateField(blank=True, null=True)),
                        ('end_date', models.DateField(blank=True, null=True)),
                        ('implementation_requirements', models.TextField(blank=True)),
                        ('project_goals', models.TextField(blank=True)),
                        ('estimated_hours', models.IntegerField(default=0)),
                        ('supervisor', models.CharField(blank=True, max_length=200)),
                        ('duration', models.CharField(blank=True, max_length=100)),
                        ('tags', models.JSONField(blank=True, default=list)),
                        ('progress', models.IntegerField(default=0)),
                        ('organization', models.CharField(blank=True, max_length=200)),
                        ('hours', models.CharField(blank=True, max_length=50)),
                        ('is_hidden', models.BooleanField(default=False)),
                        ('budget', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                        ('external_source', models.CharField(blank=True, max_length=50)),
                        ('external_id', models.CharField(blank=True, max_length=100)),
                        ('status', models.CharField(choices=[('PLANNED', 'Planned'), ('ACTIVE', 'Active'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='PLANNED', max_length=20)),
                        ('created_at', models.DateTimeField(auto_now_add=True)),
                        ('updated_at', models.DateTimeField(auto_now=True)),
                        ('manager_employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_projects', to='analytics.employee')),
                    ],
                    options={
                        'db_table': 'takaful_app_project',
                        'ordering': ['-created_at'],
                    },
                ),
                migrations.CreateModel(
                    name='ServiceRequest',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('beneficiary_name', models.CharField(max_length=200)),
                        ('beneficiary_contact', models.CharField(blank=True, max_length=200)),
                        ('details', models.TextField(blank=True)),
                        ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('DONE', 'Done')], default='PENDING', max_length=20)),
                        ('created_at', models.DateTimeField(auto_now_add=True)),
                        ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='volunteering.service')),
                    ],
                    options={
                        'db_table': 'takaful_app_servicerequest',
                    },
                ),
                migrations.CreateModel(
                    name='Task',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('title', models.CharField(max_length=200)),
                        ('description', models.TextField(blank=True)),
                        ('status', models.CharField(choices=[('قيد التنفيذ', 'In Progress'), ('في الانتظار', 'Waiting'), ('مكتملة', 'Completed'), ('معلقة', 'On Hold'), ('ملغاة', 'Cancelled')], default='في الانتظار', max_length=20)),
                        ('priority', models.CharField(choices=[('عالية', 'High'), ('متوسطة', 'Medium'), ('منخفضة', 'Low')], default='متوسطة', max_length=20)),
                        ('due_date', models.DateField(blank=True, null=True)),
                        ('hours', models.IntegerField(default=0)),
                        ('progress', models.IntegerField(default=0)),
                        ('created_at', models.DateTimeField(auto_now_add=True)),
                        ('updated_at', models.DateTimeField(auto_now=True)),
                        ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='volunteering.project')),
                        ('volunteer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tasks', to=settings.AUTH_USER_MODEL)),
                    ],
                    options={
                        'db_table': 'takaful_app_task',
                        'ordering': ['-created_at'],
                    },
                ),
                migrations.CreateModel(
                    name='Subtask',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('title', models.CharField(max_length=200)),
                        ('completed', models.BooleanField(default=False)),
                        ('order', models.IntegerField(default=0)),
                        ('created_at', models.DateTimeField(auto_now_add=True)),
                        ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subtasks', to='volunteering.task')),
                    ],
                    options={
                        'db_table': 'takaful_app_subtask',
                        'ordering': ['order', 'created_at'],
                    },
                ),
                migrations.CreateModel(
                    name='DepartmentHours',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('department_name', models.CharField(max_length=200)),
                        ('department_name_ar', models.CharField(max_length=200)),
                        ('hours', models.IntegerField(default=0)),
                        ('percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                        ('color', models.CharField(default='#6B1F2B', max_length=20)),
                        ('statistics', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='department_hours', to='volunteering.volunteerstatistics')),
                    ],
                    options={
                        'db_table': 'takaful_app_departmenthours',
                        'ordering': ['-hours'],
                    },
                ),
                migrations.CreateModel(
                    name='ProjectAssignment',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('status', models.CharField(choices=[('جديدة', 'New'), ('قيد التنفيذ', 'In Progress'), ('معلقة', 'On Hold'), ('مكتملة', 'Completed'), ('ملغية', 'Cancelled')], default='جديدة', max_length=20)),
                        ('assigned_at', models.DateTimeField(auto_now_add=True)),
                        ('completed_at', models.DateTimeField(blank=True, null=True)),
                        ('hours_contributed', models.IntegerField(default=0)),
                        ('progress', models.IntegerField(default=0)),
                        ('notes', models.TextField(blank=True)),
                        ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='volunteering.project')),
                        ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_assignments', to=settings.AUTH_USER_MODEL)),
                    ],
                    options={
                        'db_table': 'takaful_app_projectassignment',
                        'ordering': ['-assigned_at'],
                        'unique_together': {('project', 'user')},
                    },
                ),
                migrations.CreateModel(
                    name='ServiceVolunteerApplication',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('status', models.CharField(choices=[('قيد المراجعة', 'Under Review'), ('مقبول', 'Accepted'), ('مرفوض', 'Rejected')], default='قيد المراجعة', max_length=20)),
                        ('message', models.TextField(blank=True)),
                        ('admin_notes', models.TextField(blank=True)),
                        ('applied_at', models.DateTimeField(auto_now_add=True)),
                        ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                        ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_service_applications', to=settings.AUTH_USER_MODEL)),
                        ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='volunteer_applications', to='volunteering.service')),
                        ('volunteer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_applications', to=settings.AUTH_USER_MODEL)),
                    ],
                    options={
                        'db_table': 'takaful_app_servicevolunteerapplication',
                        'ordering': ['-applied_at'],
                        'unique_together': {('volunteer', 'service')},
                    },
                ),
                migrations.CreateModel(
                    name='VolunteerApplication',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('status', models.CharField(choices=[('قيد المراجعة', 'Under Review'), ('مقبول', 'Accepted'), ('مرفوض', 'Rejected')], default='قيد المراجعة', max_length=20)),
                        ('message', models.TextField(blank=True)),
                        ('admin_notes', models.TextField(blank=True)),
                        ('applied_at', models.DateTimeField(auto_now_add=True)),
                        ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                        ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='volunteering.project')),
                        ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_applications', to=settings.AUTH_USER_MODEL)),
                        ('volunteer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='volunteer_applications', to=settings.AUTH_USER_MODEL)),
                    ],
                    options={
                        'db_table': 'takaful_app_volunteerapplication',
                        'ordering': ['-applied_at'],
                        'unique_together': {('volunteer', 'project')},
                    },
                ),
                migrations.CreateModel(
                    name='TopVolunteer',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('rank', models.IntegerField()),
                        ('name', models.CharField(max_length=200)),
                        ('hours', models.IntegerField(default=0)),
                        ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                        ('statistics', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='top_volunteers', to='volunteering.volunteerstatistics')),
                    ],
                    options={
                        'db_table': 'takaful_app_topvolunteer',
                        'ordering': ['rank'],
                        'unique_together': {('statistics', 'rank')},
                    },
                ),
                migrations.CreateModel(
                    name='QuarterlyTarget',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('quarter', models.IntegerField(choices=[(1, 'Q1 - الربع الأول'), (2, 'Q2 - الربع الثاني'), (3, 'Q3 - الربع الثالث'), (4, 'Q4 - الربع الرابع')])),
                        ('volunteer_target', models.IntegerField(default=0)),
                        ('volunteer_actual', models.IntegerField(default=0)),
                        ('hours_target', models.IntegerField(default=0)),
                        ('hours_actual', models.IntegerField(default=0)),
                        ('statistics', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quarterly_targets', to='volunteering.volunteerstatistics')),
                    ],
                    options={
                        'db_table': 'takaful_app_quarterlytarget',
                        'ordering': ['quarter'],
                        'unique_together': {('statistics', 'quarter')},
                    },
                ),
            ],
            database_operations=[],
        ),
    ]
