# Generated by Django 5.2.17 on 2026-09-15 05:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_project_allowed_supplier_rep'),
        ('volunteering', '0005_split_apps'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OpportunityRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=30)),
                ('national_id', models.CharField(max_length=20)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('gender', models.CharField(blank=True, max_length=10)),
                ('age', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('qualification', models.CharField(blank=True, max_length=100)),
                ('source', models.CharField(choices=[('existing_user', 'مستخدم حالي'), ('guest', 'متطوع')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'قيد التحقق'), ('confirmed', 'مؤكَّد'), ('approved', 'معتمد كمستخدم'), ('rejected', 'مرفوض')], default='pending', max_length=20)),
                ('email_verified_at', models.DateTimeField(blank=True, null=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('admin_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opportunity_registrations', to='projects.project')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_opportunity_registrations', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='opportunity_registrations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'volunteering_opportunity_registration',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['project', 'status'], name='idx_opp_reg_project_status'), models.Index(fields=['email'], name='idx_opp_reg_email')],
                'constraints': [models.UniqueConstraint(fields=('project', 'national_id', 'phone'), name='uq_opportunity_reg_project_nid_phone')],
            },
        ),
    ]
