# Generated by Django 5.2.8 on 2025-11-14 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('takaful_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='collected_amount',
        ),
        migrations.RemoveField(
            model_name='project',
            name='description',
        ),
        migrations.RemoveField(
            model_name='project',
            name='target_amount',
        ),
        migrations.AddField(
            model_name='project',
            name='beneficiaries',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='project',
            name='category',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='project',
            name='desc',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='project',
            name='location',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
