# Generated by Django 5.2.8 on 2025-11-14 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('takaful_app', '0002_remove_project_collected_amount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='description',
        ),
        migrations.RemoveField(
            model_name='service',
            name='name',
        ),
        migrations.AddField(
            model_name='service',
            name='desc',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='service',
            name='status',
            field=models.CharField(choices=[('متاحة', 'متاحة'), ('قادمة', 'قادمة'), ('مكتملة', 'مكتملة')], default='متاحة', max_length=20),
        ),
        migrations.AddField(
            model_name='service',
            name='title',
            field=models.CharField(default='خدمة', max_length=200),
            preserve_default=False,
        ),
    ]
