# Generated by Django 5.2.8 on 2025-12-30 21:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('takaful_app', '0003_remove_service_description_remove_service_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='duration',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='project',
            name='estimated_hours',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='project',
            name='supervisor',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.CreateModel(
            name='ProjectAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('جديدة', 'New'), ('قيد التنفيذ', 'In Progress'), ('معلقة', 'On Hold'), ('مكتملة', 'Completed'), ('ملغية', 'Cancelled')], default='جديدة', max_length=20)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('hours_contributed', models.IntegerField(default=0)),
                ('progress', models.IntegerField(default=0)),
                ('notes', models.TextField(blank=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='takaful_app.project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-assigned_at'],
                'unique_together': {('project', 'user')},
            },
        ),
    ]
