# Generated by Django 5.2.8 on 2025-12-31 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('takaful_app', '0005_alter_project_options_project_donation_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='hours',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='project',
            name='organization',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='project',
            name='progress',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='project',
            name='tags',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
