# Generated by Django 5.2.8 on 2025-12-31 13:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('takaful_app', '0006_project_hours_project_organization_project_progress_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('قيد التنفيذ', 'In Progress'), ('في الانتظار', 'Waiting'), ('مكتملة', 'Completed'), ('معلقة', 'On Hold')], default='في الانتظار', max_length=20)),
                ('priority', models.CharField(choices=[('عالية', 'High'), ('متوسطة', 'Medium'), ('منخفضة', 'Low')], default='متوسطة', max_length=20)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('hours', models.IntegerField(default=0)),
                ('progress', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='takaful_app.project')),
                ('volunteer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tasks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Subtask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('completed', models.BooleanField(default=False)),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subtasks', to='takaful_app.task')),
            ],
            options={
                'ordering': ['order', 'created_at'],
            },
        ),
    ]
