# Generated by Django 5.2.8 on 2026-01-11 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('takaful_app', '0010_volunteerapplication'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('قيد التنفيذ', 'In Progress'), ('في الانتظار', 'Waiting'), ('مكتملة', 'Completed'), ('معلقة', 'On Hold'), ('ملغاة', 'Cancelled')], default='في الانتظار', max_length=20),
        ),
    ]
