# Generated by Django 5.2.8 on 2026-01-16 16:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('takaful_app', '0011_alter_task_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='service_type',
            field=models.CharField(choices=[('للمستفيدين', 'للمستفيدين'), ('للمتطوعين', 'للمتطوعين')], default='للمتطوعين', max_length=20),
        ),
        migrations.CreateModel(
            name='ServiceVolunteerApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('قيد المراجعة', 'Under Review'), ('مقبول', 'Accepted'), ('مرفوض', 'Rejected')], default='قيد المراجعة', max_length=20)),
                ('message', models.TextField(blank=True)),
                ('admin_notes', models.TextField(blank=True)),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_service_applications', to=settings.AUTH_USER_MODEL)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='volunteer_applications', to='takaful_app.service')),
                ('volunteer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_applications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-applied_at'],
                'unique_together': {('volunteer', 'service')},
            },
        ),
    ]
