# Generated by Django 5.2.8 on 2026-02-28 11:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('takaful_app', '0012_service_service_type_servicevolunteerapplication'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VolunteerStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(unique=True)),
                ('total_volunteers', models.IntegerField(default=0)),
                ('new_volunteers', models.IntegerField(default=0)),
                ('returning_volunteers', models.IntegerField(default=0)),
                ('total_hours', models.IntegerField(default=0)),
                ('total_contribution_value', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('contribution_value_display', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Volunteer Statistics',
                'ordering': ['-year'],
            },
        ),
        migrations.CreateModel(
            name='DepartmentHours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_name', models.CharField(max_length=200)),
                ('department_name_ar', models.CharField(max_length=200)),
                ('hours', models.IntegerField(default=0)),
                ('percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('color', models.CharField(default='#6B1F2B', max_length=20)),
                ('statistics', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='department_hours', to='takaful_app.volunteerstatistics')),
            ],
            options={
                'ordering': ['-hours'],
            },
        ),
        migrations.CreateModel(
            name='TopVolunteer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.IntegerField()),
                ('name', models.CharField(max_length=200)),
                ('hours', models.IntegerField(default=0)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('statistics', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='top_volunteers', to='takaful_app.volunteerstatistics')),
            ],
            options={
                'ordering': ['rank'],
                'unique_together': {('statistics', 'rank')},
            },
        ),
        migrations.CreateModel(
            name='QuarterlyTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quarter', models.IntegerField(choices=[(1, 'Q1 - الربع الأول'), (2, 'Q2 - الربع الثاني'), (3, 'Q3 - الربع الثالث'), (4, 'Q4 - الربع الرابع')])),
                ('volunteer_target', models.IntegerField(default=0)),
                ('volunteer_actual', models.IntegerField(default=0)),
                ('hours_target', models.IntegerField(default=0)),
                ('hours_actual', models.IntegerField(default=0)),
                ('statistics', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quarterly_targets', to='takaful_app.volunteerstatistics')),
            ],
            options={
                'ordering': ['quarter'],
                'unique_together': {('statistics', 'quarter')},
            },
        ),
    ]
