# Generated by Django 5.2.8 on 2026-03-02 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('takaful_app', '0013_volunteer_statistics'),
    ]

    operations = [
        migrations.CreateModel(
            name='WaterSupplyRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applicant_name', models.CharField(max_length=200)),
                ('mobile_number', models.CharField(max_length=20)),
                ('applicant_role', models.CharField(choices=[('إمام', 'إمام'), ('مؤذن', 'مؤذن'), ('غير ذلك', 'غير ذلك')], max_length=50)),
                ('mosque_name', models.CharField(max_length=200)),
                ('neighborhood', models.CharField(max_length=200)),
                ('location_link', models.URLField(max_length=500)),
                ('worshippers_count', models.IntegerField()),
                ('donor_exists', models.BooleanField(default=False)),
                ('donor_name', models.CharField(blank=True, max_length=200)),
                ('donor_phone', models.CharField(blank=True, max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'قيد المراجعة'), ('APPROVED', 'مقبول'), ('REJECTED', 'مرفوض'), ('COMPLETED', 'مكتمل')], default='PENDING', max_length=20)),
                ('admin_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
