# Generated by Django 5.2.15 on 2026-08-01 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('takaful_app', '0015_project_budget_project_external_id_and_more'),
        # تُنشأ حالة النماذج في volunteering قبل حذفها من takaful_app
        ('volunteering', '0001_initial'),
    ]

    # نقل نماذج بين تطبيقات دون لمس البيانات (DECISIONS.md D-02):
    # عمليات حالة فقط — الجداول الفعلية تبقى كما أنشأتها هجرات التطبيق الأصلي.
    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.RemoveField(
                    model_name='adminreport',
                    name='admin',
                ),
                migrations.RemoveField(
                    model_name='departmenthours',
                    name='statistics',
                ),
                migrations.RemoveField(
                    model_name='project',
                    name='manager_employee',
                ),
                migrations.RemoveField(
                    model_name='volunteerapplication',
                    name='project',
                ),
                migrations.RemoveField(
                    model_name='task',
                    name='project',
                ),
                migrations.RemoveField(
                    model_name='projectassignment',
                    name='project',
                ),
                migrations.AlterUniqueTogether(
                    name='projectassignment',
                    unique_together=None,
                ),
                migrations.RemoveField(
                    model_name='projectassignment',
                    name='user',
                ),
                migrations.AlterUniqueTogether(
                    name='quarterlytarget',
                    unique_together=None,
                ),
                migrations.RemoveField(
                    model_name='quarterlytarget',
                    name='statistics',
                ),
                migrations.RemoveField(
                    model_name='servicerequest',
                    name='service',
                ),
                migrations.RemoveField(
                    model_name='servicevolunteerapplication',
                    name='service',
                ),
                migrations.AlterUniqueTogether(
                    name='servicevolunteerapplication',
                    unique_together=None,
                ),
                migrations.RemoveField(
                    model_name='servicevolunteerapplication',
                    name='reviewed_by',
                ),
                migrations.RemoveField(
                    model_name='servicevolunteerapplication',
                    name='volunteer',
                ),
                migrations.RemoveField(
                    model_name='subtask',
                    name='task',
                ),
                migrations.DeleteModel(
                    name='Suggestion',
                ),
                migrations.RemoveField(
                    model_name='task',
                    name='volunteer',
                ),
                migrations.AlterUniqueTogether(
                    name='topvolunteer',
                    unique_together=None,
                ),
                migrations.RemoveField(
                    model_name='topvolunteer',
                    name='statistics',
                ),
                migrations.RemoveField(
                    model_name='topvolunteer',
                    name='user',
                ),
                migrations.DeleteModel(
                    name='Volunteer',
                ),
                migrations.AlterUniqueTogether(
                    name='volunteerapplication',
                    unique_together=None,
                ),
                migrations.RemoveField(
                    model_name='volunteerapplication',
                    name='reviewed_by',
                ),
                migrations.RemoveField(
                    model_name='volunteerapplication',
                    name='volunteer',
                ),
                migrations.DeleteModel(
                    name='WaterSupplyRequest',
                ),
                migrations.DeleteModel(
                    name='AdminReport',
                ),
                migrations.DeleteModel(
                    name='DepartmentHours',
                ),
            ],
            database_operations=[],
        ),
    ]
