# Generated by Django 5.2.15 on 2026-08-01 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_alter_stafftask_project'),
        ('takaful_app', '0016_remove_adminreport_admin_and_more'),
    ]

    # نقل نماذج بين تطبيقات دون لمس البيانات (DECISIONS.md D-02):
    # عمليات حالة فقط — الجداول الفعلية تبقى كما أنشأتها هجرات التطبيق الأصلي.
    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.DeleteModel(
                    name='Project',
                ),
                migrations.DeleteModel(
                    name='ProjectAssignment',
                ),
                migrations.DeleteModel(
                    name='QuarterlyTarget',
                ),
                migrations.DeleteModel(
                    name='ServiceRequest',
                ),
                migrations.DeleteModel(
                    name='Service',
                ),
                migrations.DeleteModel(
                    name='ServiceVolunteerApplication',
                ),
                migrations.DeleteModel(
                    name='Subtask',
                ),
                migrations.DeleteModel(
                    name='Task',
                ),
                migrations.DeleteModel(
                    name='VolunteerStatistics',
                ),
                migrations.DeleteModel(
                    name='TopVolunteer',
                ),
                migrations.DeleteModel(
                    name='VolunteerApplication',
                ),
            ],
            database_operations=[],
        ),
    ]
