# Generated by Django 5.2.17 on 2026-09-16 21:30

import django.db.models.deletion
import projectdocs.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0006_project_allowed_supplier_rep'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectDossier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=32, unique=True)),
                ('marketing_name', models.CharField(blank=True, max_length=200)),
                ('portfolio', models.CharField(blank=True, max_length=200)),
                ('department', models.CharField(blank=True, max_length=200)),
                ('section', models.CharField(blank=True, max_length=200)),
                ('strategic_goal', models.TextField(blank=True)),
                ('location', models.CharField(blank=True, max_length=300)),
                ('projects_office_name', models.CharField(blank=True, help_text='عرض فقط', max_length=200)),
                ('projects_committee_name', models.CharField(blank=True, help_text='عرض فقط', max_length=200)),
                ('sponsor_name', models.CharField(blank=True, max_length=200)),
                ('sponsor_email', models.EmailField(blank=True, max_length=254)),
                ('manager_email', models.EmailField(blank=True, max_length=254)),
                ('current_stage', models.CharField(choices=[('define', 'التعريف'), ('prepare', 'التجهيز'), ('plan', 'التخطيط'), ('execute', 'التنفيذ'), ('close', 'الإغلاق')], default='define', max_length=20)),
                ('status', models.CharField(choices=[('draft', 'مسودة'), ('in_progress', 'قيد التنفيذ'), ('pending_approval', 'بانتظار الاعتماد'), ('approved', 'معتمد'), ('closed', 'مغلق')], default='draft', max_length=30)),
                ('budget_association', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('budget_donation', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('budget_total', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_dossiers', to=settings.AUTH_USER_MODEL)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dossier', to='projects.project')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DossierStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField()),
                ('key', models.CharField(choices=[('define', 'التعريف'), ('prepare', 'التجهيز'), ('plan', 'التخطيط'), ('execute', 'التنفيذ'), ('close', 'الإغلاق')], max_length=20)),
                ('planned_start', models.DateField(blank=True, null=True)),
                ('planned_end', models.DateField(blank=True, null=True)),
                ('deliverable_title', models.CharField(blank=True, max_length=300)),
                ('deliverable_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('locked', 'مقفلة'), ('active', 'نشطة'), ('submitted', 'بانتظار الاعتماد'), ('approved', 'معتمدة'), ('returned', 'معادة للتعديل')], default='locked', max_length=20)),
                ('return_note', models.TextField(blank=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dossier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='projectdocs.projectdossier')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='DossierSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('document', 'وثيقة المشروع'), ('closure', 'وثيقة الإغلاق')], max_length=20)),
                ('key', models.CharField(max_length=64)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('empty', 'فارغ'), ('filled', 'معبّأ'), ('submitted', 'مُرسل'), ('approved', 'معتمد'), ('returned', 'معاد للتعديل')], default='empty', max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('dossier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='projectdocs.projectdossier')),
            ],
            options={
                'ordering': ['kind', 'key'],
            },
        ),
        migrations.CreateModel(
            name='DossierAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_key', models.CharField(blank=True, max_length=64)),
                ('title', models.CharField(blank=True, max_length=200)),
                ('file', models.FileField(blank=True, upload_to=projectdocs.models.dossier_attachment_path)),
                ('external_url', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('stage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attachments', to='projectdocs.dossierstage')),
                ('dossier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='projectdocs.projectdossier')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ApprovalRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope', models.CharField(choices=[('card', 'البطاقة'), ('stage', 'مرحلة'), ('document', 'الوثيقة'), ('closure', 'الإغلاق')], max_length=20)),
                ('token', models.CharField(db_index=True, max_length=64, unique=True)),
                ('expires_at', models.DateTimeField()),
                ('decision', models.CharField(choices=[('pending', 'بانتظار'), ('approved', 'معتمد'), ('returned', 'إعادة للتعديل'), ('expired', 'منتهي')], default='pending', max_length=20)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('note', models.TextField(blank=True)),
                ('payload_snapshot', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('stage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approvals', to='projectdocs.dossierstage')),
                ('dossier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to='projectdocs.projectdossier')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StageActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=40)),
                ('title', models.CharField(max_length=300)),
                ('responsible', models.CharField(blank=True, max_length=200)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('manual_status', models.CharField(blank=True, choices=[('', '—'), ('in_progress', 'جاري التنفيذ'), ('done', 'تم التنفيذ')], default='', max_length=20)),
                ('auto_status', models.CharField(choices=[('not_due', 'لم يحن'), ('in_progress', 'جاري'), ('done', 'منفذ'), ('delayed', 'متعثر'), ('stopped', 'موقوف')], default='not_due', max_length=20)),
                ('progress_pct', models.PositiveSmallIntegerField(default=0)),
                ('kpi', models.CharField(blank=True, max_length=300)),
                ('sponsor_rating', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('lessons', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('risks', models.TextField(blank=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='projectdocs.stageactivity')),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='projectdocs.dossierstage')),
            ],
            options={
                'ordering': ['sort_order', 'code', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='projectdossier',
            index=models.Index(fields=['status', 'current_stage'], name='projectdocs_status_e709ed_idx'),
        ),
        migrations.AddIndex(
            model_name='projectdossier',
            index=models.Index(fields=['sponsor_email'], name='projectdocs_sponsor_c1eeae_idx'),
        ),
        migrations.AddConstraint(
            model_name='dossierstage',
            constraint=models.UniqueConstraint(fields=('dossier', 'order'), name='uq_dossier_stage_order'),
        ),
        migrations.AddConstraint(
            model_name='dossierstage',
            constraint=models.UniqueConstraint(fields=('dossier', 'key'), name='uq_dossier_stage_key'),
        ),
        migrations.AddIndex(
            model_name='dossiersection',
            index=models.Index(fields=['dossier', 'kind', 'status'], name='projectdocs_dossier_11290e_idx'),
        ),
        migrations.AddConstraint(
            model_name='dossiersection',
            constraint=models.UniqueConstraint(fields=('dossier', 'kind', 'key'), name='uq_dossier_section'),
        ),
        migrations.AddIndex(
            model_name='approvalrequest',
            index=models.Index(fields=['decision', 'expires_at'], name='projectdocs_decisio_56cc44_idx'),
        ),
        migrations.AddIndex(
            model_name='stageactivity',
            index=models.Index(fields=['stage', 'auto_status'], name='projectdocs_stage_i_68c1e7_idx'),
        ),
    ]
