# Generated by Django 5.2.17 on 2026-09-22 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectdocs', '0002_budget_lines_activity_evidence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dossierstage',
            name='key',
            field=models.CharField(choices=[('define', 'تحديد وتعريف المشروع'), ('prepare', 'إعداد المشروع'), ('plan', 'التخطيط للمشروع'), ('execute', 'تنفيذ المشروع'), ('close', 'إغلاق المشروع')], max_length=20),
        ),
        migrations.AlterField(
            model_name='projectdossier',
            name='current_stage',
            field=models.CharField(choices=[('define', 'تحديد وتعريف المشروع'), ('prepare', 'إعداد المشروع'), ('plan', 'التخطيط للمشروع'), ('execute', 'تنفيذ المشروع'), ('close', 'إغلاق المشروع')], default='define', max_length=20),
        ),
    ]
