# Generated by Django 5.2.17 on 2026-09-22 07:44

import django.db.models.deletion
from django.db import migrations, models


def backfill_workspaces(apps, schema_editor):
    ProjectDossier = apps.get_model("projectdocs", "ProjectDossier")
    DossierWorkspace = apps.get_model("projectdocs", "DossierWorkspace")
    specs = [
        (1, "card", "approved"),
        (2, "document", "active"),
        (3, "plan", "locked"),
        (4, "closure", "locked"),
        (5, "board", "locked"),
    ]
    for d in ProjectDossier.objects.all():
        if DossierWorkspace.objects.filter(dossier=d).exists():
            continue
        DossierWorkspace.objects.bulk_create(
            [
                DossierWorkspace(dossier=d, order=order, key=key, status=status)
                for order, key, status in specs
            ]
        )


class Migration(migrations.Migration):

    dependencies = [
        ("projectdocs", "0003_stage_labels_excel_ar"),
    ]

    operations = [
        migrations.AlterField(
            model_name="approvalrequest",
            name="scope",
            field=models.CharField(
                choices=[
                    ("card", "البطاقة"),
                    ("stage", "مرحلة"),
                    ("document", "الوثيقة"),
                    ("plan", "الخطة التنفيذية"),
                    ("closure", "الإغلاق"),
                    ("board", "لوحة المشروع"),
                ],
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="DossierWorkspace",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("order", models.PositiveSmallIntegerField()),
                (
                    "key",
                    models.CharField(
                        choices=[
                            ("card", "البطاقة"),
                            ("document", "الوثيقة"),
                            ("plan", "الخطة التنفيذية"),
                            ("closure", "الإغلاق"),
                            ("board", "لوحة المشروع"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("locked", "مقفلة"),
                            ("active", "نشطة"),
                            ("submitted", "بانتظار الاعتماد"),
                            ("approved", "معتمدة"),
                            ("returned", "معادة للتعديل"),
                        ],
                        default="locked",
                        max_length=20,
                    ),
                ),
                ("return_note", models.TextField(blank=True)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "dossier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="workspaces",
                        to="projectdocs.projectdossier",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
                "constraints": [
                    models.UniqueConstraint(fields=("dossier", "order"), name="uq_dossier_workspace_order"),
                    models.UniqueConstraint(fields=("dossier", "key"), name="uq_dossier_workspace_key"),
                ],
            },
        ),
        migrations.RunPython(backfill_workspaces, migrations.RunPython.noop),
    ]
