# Generated by Django 5.2.15 on 2026-08-09 05:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("volunteering", "0004_swap_project_fks"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('desc', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('متاحة', 'متاحة'), ('قادمة', 'قادمة'), ('مكتملة', 'مكتملة')], default='متاحة', max_length=20)),
                ('service_type', models.CharField(choices=[('للمستفيدين', 'للمستفيدين'), ('للمتطوعين', 'للمتطوعين')], default='للمتطوعين', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'takaful_app_service',
            },
        ),
        migrations.CreateModel(
            name='Suggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('submitted_by', models.CharField(blank=True, max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_reviewed', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'takaful_app_suggestion',
            },
        ),
        migrations.CreateModel(
            name='WaterSupplyRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applicant_name', models.CharField(max_length=200)),
                ('mobile_number', models.CharField(max_length=20)),
                ('applicant_role', models.CharField(choices=[('إمام', 'إمام'), ('مؤذن', 'مؤذن'), ('غير ذلك', 'غير ذلك')], max_length=50)),
                ('mosque_name', models.CharField(max_length=200)),
                ('neighborhood', models.CharField(max_length=200)),
                ('location_link', models.URLField(max_length=500)),
                ('worshippers_count', models.IntegerField()),
                ('donor_exists', models.BooleanField(default=False)),
                ('donor_name', models.CharField(blank=True, max_length=200)),
                ('donor_phone', models.CharField(blank=True, max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'قيد المراجعة'), ('APPROVED', 'مقبول'), ('REJECTED', 'مرفوض'), ('COMPLETED', 'مكتمل')], default='PENDING', max_length=20)),
                ('admin_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'takaful_app_watersupplyrequest',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ServiceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beneficiary_name', models.CharField(max_length=200)),
                ('beneficiary_contact', models.CharField(blank=True, max_length=200)),
                ('details', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('DONE', 'Done')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='services.service')),
            ],
            options={
                'db_table': 'takaful_app_servicerequest',
            },
        ),
        migrations.CreateModel(
            name='ServiceVolunteerApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('قيد المراجعة', 'Under Review'), ('مقبول', 'Accepted'), ('مرفوض', 'Rejected')], default='قيد المراجعة', max_length=20)),
                ('message', models.TextField(blank=True)),
                ('admin_notes', models.TextField(blank=True)),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_service_applications', to=settings.AUTH_USER_MODEL)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='volunteer_applications', to='services.service')),
                ('volunteer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_applications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'takaful_app_servicevolunteerapplication',
                'ordering': ['-applied_at'],
                'unique_together': {('volunteer', 'service')},
            },
        ),
            ],
        ),
    ]
