# Generated by Django 5.2.15 on 2026-08-17 06:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_featured_home'),
        ('services', '0001_split_apps'),
    ]

    operations = [
        migrations.AddField(
            model_name='watersupplyrequest',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='water_supply_requests', to='projects.project'),
        ),
    ]
