# Generated by Django 5.2.8 on 2026-06-26 03:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('takaful_app', '0014_water_supply_request'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardKpi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('value', models.CharField(max_length=50)),
                ('subtitle', models.CharField(blank=True, max_length=150)),
                ('icon_key', models.CharField(blank=True, max_length=50)),
                ('display_order', models.IntegerField(default=0)),
                ('external_source', models.CharField(blank=True, max_length=50)),
                ('external_id', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['display_order', 'id'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('external_id', ''), _negated=True), fields=('external_source', 'external_id'), name='uq_dashboard_kpi_external')],
            },
        ),
        migrations.CreateModel(
            name='DashboardSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('unit', models.CharField(blank=True, max_length=50)),
                ('total', models.IntegerField(default=0)),
                ('actual', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('expected', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('closed', models.IntegerField(default=0)),
                ('in_progress', models.IntegerField(default=0)),
                ('near', models.IntegerField(default=0)),
                ('late', models.IntegerField(default=0)),
                ('review', models.IntegerField(default=0)),
                ('not_started', models.IntegerField(default=0)),
                ('icon_key', models.CharField(blank=True, max_length=50)),
                ('display_order', models.IntegerField(default=0)),
                ('external_source', models.CharField(blank=True, max_length=50)),
                ('external_id', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['display_order', 'id'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('external_id', ''), _negated=True), fields=('external_source', 'external_id'), name='uq_dashboard_section_external')],
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('role', models.CharField(blank=True, max_length=150)),
                ('completed_tasks', models.IntegerField(default=0)),
                ('progress', models.IntegerField(default=0)),
                ('icon_key', models.CharField(blank=True, max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('external_source', models.CharField(blank=True, max_length=50)),
                ('external_id', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-progress', 'name'],
            },
        ),
        migrations.CreateModel(
            name='StaffTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('initiative', models.CharField(blank=True, max_length=200)),
                ('completed_date', models.DateField(blank=True, null=True)),
                ('progress', models.IntegerField(default=0)),
                ('external_source', models.CharField(blank=True, max_length=50)),
                ('external_id', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_tasks', to='analytics.employee')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_tasks', to='takaful_app.project')),
            ],
            options={
                'ordering': ['-completed_date', '-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['is_active'], name='analytics_e_is_acti_523c2d_idx'),
        ),
        migrations.AddConstraint(
            model_name='employee',
            constraint=models.UniqueConstraint(condition=models.Q(('external_id', ''), _negated=True), fields=('external_source', 'external_id'), name='uq_employee_external'),
        ),
        migrations.AddConstraint(
            model_name='stafftask',
            constraint=models.UniqueConstraint(condition=models.Q(('external_id', ''), _negated=True), fields=('external_source', 'external_id'), name='uq_staff_task_external'),
        ),
    ]
