# Generated by Django 5.2.15 on 2026-08-01 14:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
        ('volunteering', '0001_initial'),
    ]

    # نقل نماذج بين تطبيقات دون لمس البيانات (DECISIONS.md D-02):
    # عمليات حالة فقط — الجداول الفعلية تبقى كما أنشأتها هجرات التطبيق الأصلي.
    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterField(
                    model_name='stafftask',
                    name='project',
                    field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_tasks', to='volunteering.project'),
                ),
            ],
            database_operations=[],
        ),
    ]
