# Generated by Django 5.2.15 on 2026-08-01 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('saqya', '0001_initial'),
        # تُنشأ حالة النماذج في sponsorships قبل حذفها من saqya
        ('sponsorships', '0001_initial'),
    ]

    # نقل نماذج بين تطبيقات دون لمس البيانات (DECISIONS.md D-02):
    # عمليات حالة فقط — الجداول الفعلية تبقى كما أنشأتها هجرات التطبيق الأصلي.
    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.RemoveField(
                    model_name='invoice',
                    name='order',
                ),
                migrations.RemoveField(
                    model_name='order',
                    name='representative',
                ),
                migrations.RemoveField(
                    model_name='order',
                    name='sponsorship',
                ),
                migrations.RemoveField(
                    model_name='order',
                    name='supplier',
                ),
                migrations.RemoveField(
                    model_name='payment',
                    name='sponsorship',
                ),
                migrations.RemoveField(
                    model_name='representativeprofile',
                    name='user',
                ),
                migrations.RemoveField(
                    model_name='sponsorship',
                    name='donor',
                ),
                migrations.RemoveField(
                    model_name='supplierprofile',
                    name='user',
                ),
                migrations.DeleteModel(
                    name='Documentation',
                ),
                migrations.DeleteModel(
                    name='Invoice',
                ),
                migrations.DeleteModel(
                    name='Order',
                ),
                migrations.DeleteModel(
                    name='Payment',
                ),
                migrations.DeleteModel(
                    name='RepresentativeProfile',
                ),
                migrations.DeleteModel(
                    name='Sponsorship',
                ),
                migrations.DeleteModel(
                    name='SupplierProfile',
                ),
            ],
            database_operations=[],
        ),
    ]
