# Generated by Django 5.2.15 on 2026-08-01 14:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
        ('sponsorships', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sponsorship',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sponsorships', to='projects.project'),
        ),
    ]
