# Generated by Django 5.2.15 on 2026-09-03 06:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_project_type'),
        ('sponsorships', '0003_link_sponsorships_to_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='sponsorship',
            name='type_data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.CreateModel(
            name='SponsorshipType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(allow_unicode=True, max_length=140)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('fields', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sponsorship_types', to='projects.project')),
            ],
            options={
                'db_table': 'saqya_sponsorshiptype',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='sponsorship',
            name='sponsorship_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sponsorships', to='sponsorships.sponsorshiptype'),
        ),
        migrations.AddConstraint(
            model_name='sponsorshiptype',
            constraint=models.UniqueConstraint(fields=('project', 'slug'), name='uq_saqya_sponsorshiptype_project_slug'),
        ),
    ]
