# Generated by Django 5.2.15 on 2026-09-04 04:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sponsorships', '0004_sponsorship_type_and_type_data'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SponsorshipStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(allow_unicode=True, max_length=40, unique=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'saqya_sponsorshipstatus',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='sponsorship',
            name='kind',
            field=models.CharField(choices=[('individual', 'individual'), ('community', 'community')], default='individual', max_length=20),
        ),
        migrations.AddField(
            model_name='sponsorship',
            name='sponsor_name',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='sponsorship',
            name='units_completed',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sponsorship',
            name='units_target',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sponsorship',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='sponsorship',
            name='donor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='saqya_sponsorships', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='sponsorship',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('approved', 'approved'), ('rejected', 'rejected'), ('in_progress', 'in_progress'), ('completed', 'completed'), ('cancelled', 'cancelled'), ('available', 'available'), ('sponsored', 'sponsored'), ('prepared', 'prepared'), ('delivered', 'delivered')], default='available', max_length=20),
        ),
        migrations.AddField(
            model_name='sponsorship',
            name='status_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sponsorships', to='sponsorships.sponsorshipstatus'),
        ),
    ]
