# Generated by Django 5.2.15 on 2026-07-04 15:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(unique=True)),
                ('icon', models.CharField(blank=True, max_length=50)),
                ('season', models.CharField(blank=True, max_length=50, null=True)),
                ('target_families', models.IntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(unique=True)),
                ('center_lat', models.FloatField()),
                ('center_lng', models.FloatField()),
                ('boundary', models.TextField(blank=True, null=True)),
                ('priority', models.CharField(choices=[('high', 'high'), ('medium', 'medium'), ('low', 'low')], default='medium', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Outlet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('type', models.CharField(choices=[('sale_point', 'sale_point'), ('permanent_corner', 'permanent_corner'), ('participation_point', 'participation_point')], max_length=30)),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
                ('address', models.TextField(blank=True)),
                ('working_hours', models.CharField(blank=True, max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outlets', to='impact_map.region')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DistributionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('families_served', models.IntegerField()),
                ('quantity_distributed', models.IntegerField()),
                ('date', models.DateField()),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='impact_distributions', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='distribution_records', to='impact_map.product')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='distribution_records', to='impact_map.region')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Contribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('phone', models.CharField(max_length=20)),
                ('quantity', models.IntegerField()),
                ('mode', models.CharField(choices=[('self_distribution', 'self_distribution'), ('delegate_association', 'delegate_association')], max_length=30)),
                ('status', models.CharField(choices=[('pending', 'pending'), ('approved', 'approved'), ('fulfilled', 'fulfilled'), ('cancelled', 'cancelled')], default='pending', max_length=20)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='impact_contributions', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contributions', to='impact_map.product')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contributions', to='impact_map.region')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
