# Generated by Django 5.2.8 on 2026-07-29 02:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('impact_map', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MapProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(unique=True)),
                ('source_type', models.CharField(choices=[('native', 'native'), ('saqya', 'saqya')], default='native', max_length=20)),
                ('icon_key', models.CharField(blank=True, max_length=50)),
                ('color', models.CharField(default='#8B1538', max_length=20)),
                ('cta_url', models.URLField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0)),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_map_projects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='contribution',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contributions', to='impact_map.mapproject'),
        ),
        migrations.AddField(
            model_name='distributionrecord',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='distribution_records', to='impact_map.mapproject'),
        ),
        migrations.AddField(
            model_name='outlet',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='outlets', to='impact_map.mapproject'),
        ),
        migrations.AddField(
            model_name='product',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='impact_map.mapproject'),
        ),
        migrations.AddField(
            model_name='region',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='regions', to='impact_map.mapproject'),
        ),
        migrations.CreateModel(
            name='ProjectMapLayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('layer_key', models.CharField(max_length=40)),
                ('label', models.CharField(blank=True, max_length=120)),
                ('marker_type', models.CharField(blank=True, max_length=40)),
                ('icon_key', models.CharField(blank=True, max_length=50)),
                ('color', models.CharField(blank=True, max_length=20)),
                ('enabled', models.BooleanField(default=True)),
                ('kpi_keys', models.JSONField(blank=True, default=list)),
                ('order', models.IntegerField(default=0)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='layers', to='impact_map.mapproject')),
            ],
            options={
                'ordering': ['order', 'id'],
                'constraints': [models.UniqueConstraint(fields=('project', 'layer_key', 'marker_type'), name='uq_projectmaplayer_key')],
            },
        ),
    ]
