# Generated by Django 5.2.15 on 2026-08-01 14:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Map',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('visibility', models.CharField(choices=[('public', 'public'), ('private', 'private'), ('mixed', 'mixed')], default='public', max_length=10)),
                ('icon_set', models.JSONField(blank=True, default=dict)),
                ('color_scheme', models.JSONField(blank=True, default=dict)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_maps', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maps', to='projects.project')),
            ],
            options={
                'ordering': ['project', 'title'],
            },
        ),
        migrations.CreateModel(
            name='MapItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
                ('name', models.CharField(max_length=200)),
                ('icon', models.CharField(blank=True, max_length=50)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('active', 'active'), ('hidden', 'hidden'), ('archived', 'archived')], default='active', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_map_items', to=settings.AUTH_USER_MODEL)),
                ('map', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='maps.map')),
            ],
            options={
                'ordering': ['map', 'layer', 'name'],
            },
        ),
        migrations.CreateModel(
            name='MapContribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(blank=True, max_length=120)),
                ('name', models.CharField(max_length=150)),
                ('phone', models.CharField(max_length=20)),
                ('mode', models.CharField(choices=[('self_distribution', 'self_distribution'), ('delegate_association', 'delegate_association')], max_length=30)),
                ('quantity', models.IntegerField()),
                ('note', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'pending'), ('approved', 'approved'), ('fulfilled', 'fulfilled'), ('cancelled', 'cancelled')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('map', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contributions', to='maps.map')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='map_contributions', to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contributions', to='maps.mapitem')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MapItemField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(max_length=60)),
                ('label', models.CharField(max_length=120)),
                ('type', models.CharField(choices=[('text', 'text'), ('number', 'number'), ('select', 'select'), ('boolean', 'boolean'), ('date', 'date')], default='text', max_length=10)),
                ('required', models.BooleanField(default=False)),
                ('options', models.JSONField(blank=True, default=list)),
                ('is_public', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0)),
                ('map', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_fields', to='maps.map')),
            ],
            options={
                'ordering': ['map', 'order', 'key'],
            },
        ),
        migrations.CreateModel(
            name='MapLayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('visibility', models.CharField(choices=[('public', 'public'), ('private', 'private')], default='public', max_length=10)),
                ('order', models.IntegerField(default=0)),
                ('style', models.JSONField(blank=True, default=dict)),
                ('map', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='layers', to='maps.map')),
            ],
            options={
                'ordering': ['map', 'order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='mapitem',
            name='layer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='maps.maplayer'),
        ),
        migrations.AddIndex(
            model_name='map',
            index=models.Index(fields=['project', 'visibility'], name='maps_map_project_f39007_idx'),
        ),
        migrations.AddIndex(
            model_name='mapcontribution',
            index=models.Index(fields=['map', 'status'], name='maps_mapcon_map_id_d96b6c_idx'),
        ),
        migrations.AddIndex(
            model_name='mapitemfield',
            index=models.Index(fields=['map', 'is_public'], name='maps_mapite_map_id_c871db_idx'),
        ),
        migrations.AddConstraint(
            model_name='mapitemfield',
            constraint=models.UniqueConstraint(fields=('map', 'key'), name='uq_map_field_key'),
        ),
        migrations.AddIndex(
            model_name='maplayer',
            index=models.Index(fields=['map', 'visibility'], name='maps_maplay_map_id_8cdf53_idx'),
        ),
        migrations.AddIndex(
            model_name='mapitem',
            index=models.Index(fields=['map', 'status'], name='maps_mapite_map_id_d59f63_idx'),
        ),
        migrations.AddIndex(
            model_name='mapitem',
            index=models.Index(fields=['layer', 'status'], name='maps_mapite_layer_i_4567ed_idx'),
        ),
    ]
