# Generated by Django 5.2.15 on 2026-08-24 04:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0003_mapproduct_mapdistributionrecord'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='mapdistributionrecord',
            new_name='maps_mapdis_map_id_9e7324_idx',
            old_name='maps_mapdis_map_id_91c4e1_idx',
        ),
        migrations.RenameIndex(
            model_name='mapdistributionrecord',
            new_name='maps_mapdis_map_id_e89913_idx',
            old_name='maps_mapdis_map_id_2b7f3c_idx',
        ),
        migrations.RenameIndex(
            model_name='mapproduct',
            new_name='maps_mappro_map_id_a3676b_idx',
            old_name='maps_mappro_map_id_6f8a2a_idx',
        ),
    ]
