# Generated by Django 5.2.15 on 2026-09-04 04:13

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_activity_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformsetting',
            name='roles_can_login',
            field=models.JSONField(blank=True, default=core.models.default_roles_can_login, help_text='أي الأدوار يُسمح لها بالحصول على جلسة دخول'),
        ),
        migrations.AddField(
            model_name='platformsetting',
            name='sponsorship_collect_donor_data',
            field=models.CharField(choices=[('none', 'none'), ('name_optional', 'name_optional'), ('full', 'full')], default='name_optional', help_text='سياسة جمع بيانات المتبرّع. زاد=name_optional', max_length=20),
        ),
        migrations.AddField(
            model_name='platformsetting',
            name='sponsorship_gps_documentation',
            field=models.BooleanField(default=False, help_text='عرض التقاط GPS عند توثيق التسليم. زاد=False'),
        ),
        migrations.AddField(
            model_name='platformsetting',
            name='sponsorship_payments_enabled',
            field=models.BooleanField(default=False, help_text='تفعيل منطق المال (جمع/متبقي/منع تجاوز التمويل). زاد=False'),
        ),
    ]
